### PR TITLE
Conversions for scala collections (continued)

### PR DESCRIPTION
**Pull request by Jolanrensen**
This continues the work from #72 and provides easy to use wrappers for Kotlin to convert between Scala and Kotlin collections.

I noticed that the conversions cannot be put in the `common` folder due to the Scala conversion functions being absent there, so I added the conversions to both 2.4 and 3.0 including some tests.

I also changed the naming, which can be discussed, to be more consistent:
```kotlin
fun <A, B> ScalaMap<A, B>.asKotlinMap(): Map<A, B>
```
and 
```kotlin
fun <A, B> Map<A, B>.asScalaMap(): ScalaMap<A, B>
```

### CODE REVIEW

**Comment by asm0dey** [comment]
Awesome contribution, thank you! Is it finished?

**Comment by asm0dey** [comment]
BTW it looks like it could be moved to the `common` module

**Comment by Jolanrensen** [comment]
> BTW it looks like it could be moved to the `common` module

For me, moving it into the common module didn't work, since that module doesn't have access to the Scala library with the conversions. You can try it yourself if you like, because it would definitely be better.
But other than that, it's finished for now :)

**Comment by asm0dey** [comment]
Oh, agreed!

Could you please fix conflicts than for me to be able to merge the PR?

**Pull request merged**
