### PR TITLE
Add enum support for `ApiV1Kt.generateEncoder`

### PR DESCRIPTION
**Pull request by nonpool**
[#98]

### CODE REVIEW

**Comment by asm0dey** [comment]
Could you please add support to 2.x Spark too?

**Comment by nonpool** [comment]
Of course. I want to use this library for our project, Could you release a new release version as soon as possible?

**Comment by asm0dey** [comment]
@nonpool I expect to release 1.0.2 on June, 19.  But if anything I can build and sign binaries for you earlier than that.

**Comment by nonpool** [comment]
OK,July 19 is the date to wait. Before that, we should fix the issue that the maven artifactId was incorrectly. [#97], I will fix this in other PR

**Comment by asm0dey** [comment]
Absolutely, thanks!

**Pull request merged**
