### PR TITLE
[feat] (Typed)Column functions fixes #54

### LINKED ISSUE #54: Add more Column comparison functions
Currently the many of the existing `Column` handy functions/operators are missing in the Kotlin API, this issue is to fulfill the gap. Here is the list of functions which can be added to the API

**Infix textual functions:**
- `infix fun Column.neq(c: Column): Column`
- `infix fun Column.geq(c: Column): Column`
- `infix fun Column.leq(c: Column): Column`
- `infix fun Column.le(c: Column): Column`
- `infix fun Column.ge(c: Column): Column`
Also need to add `infix` keyword to the existing `fun Column.eq(c: Column): Column` function

**Infix char-based functions:**
- ``infix fun Column.`>=`(c: Column): Column``
- ``infix fun Column.`<=`(c: Column): Column``
- ``infix fun Column.`>`(c: Column): Column``
- ``infix fun Column.`<`(c: Column): Column``
- ``infix fun Column.`!=`(c: Column): Column``
- ``infix fun Column.`||`(c: Column): Column``
---

Also some of the functions can be implemented via [Kotlin operator functions](https://kotlinlang.org/docs/reference/operator-overloading.html) such as `compareTo`/`multiply`/`divide`/`plus`/`minus`, but this needs to be double-checked

### PR DESCRIPTION
**Pull request by Jolanrensen**
While looking at the `select()` functions, I found a couple of ways to improve the API:

Firstly, similar to the Scala API, a `Column` can now be created from a dataset using `dataset("yourColumn")` now, as well as the usual `dataset.col("yourColumn")`.

Secondly, I walked over all `Column` operator functions in the Scala API and looked at which could be ported over to Kotlin operator or infix funs (`<` and `>=` etc. won't work, due to Kotlin limitations). I tried to avoid \`backtick\` names as they are not that easy to work with as well as staying as close to the names already in the API (so I deprecated `==` and `&&`). I'll provide a quick Scala to Kotlin guide below:

```
Scala    -> Kotlin
a == b   ->  a == b
a !== b  ->  a !== b
a === b  ->  a eq b
a =!= b  ->  a neq b
-a       ->  -a
!a       ->  !a
a > b    ->  a gt b
a < b    ->  a lt b
a <= b   ->  a leq b
a >= b   ->  a geq b
a || b   ->  a or b
a && b   ->  a and b
a + b    ->  a + b
a - b    ->  a - b
a * b    ->  a * b
a / b    ->  a / b
a % b    ->  a % b
a.between(1, 10)  -> a inRangeOf 1..10
a.getItem(0)      ->  a[0]
```
Let me know what you think!

Finally, to prepare for the `select()` functions, I looked at the `TypedColumn` functions. One of these can now be created from a normal `Column` using a new `as()` function:
```kotlin
val column: TypedColumn<Any, Int> = col("yourColumn").`as`<Int>()
```
But also, to get a `TypedColumn` specific to a certain type of `Dataset` (which is needed for the `select()` function), I added a bit of Kotlin reflection into the mix:
```kotlin
val dataset: Dataset<YourClass> = ...
val column: TypedColumn<YourClass, Int> = dataset.col(YourClass::yourColumn)
```
I also added an invoke-variant of this, so when calling `select()` on a `Dataset` you can now do:
```kotlin
dataset.select(dataset(YourClass::columnA), dataset(YourClass::columnB))
```
and it will return the right kind of typed `Dataset` :).

### CODE REVIEW

**Comment by Jolanrensen** [comment]
@asm0dey How do you feel about these additions? :)

**Comment by Jolanrensen** [comment]
Actually, slight improvement. I made a separate ```col()``` function as well, not tied to a certain `Dataset` just like in the `org.apache.spark.sql.functions`. However, since using reflection we now know the type and `TypedDataset` inherits from `Dataset`, the function returns a `TypedDataset`.

In short:
```kotlin
val dataset: Dataset<YourClass> = ...
val new: Dataset<Tuple2<TypeOfA, TypeOfB>> = dataset.select( col(YourClass::a), col(YourClass::b) )
```
This works
(The method will probably be `selectTyped` and return `Pair`s soon in a separate pull request. I've got some strange issues with a test on my end)

**Comment by asm0dey** [comment]
Could you please update README for this in PR too?
And BTW how does `==` without backticks work? Is `equals` overridden in Scala too?

**Comment by asm0dey** [comment]
Aldo Kotlin docs should definitely contain their Scala counterparts documented

**Comment by asm0dey** [comment]
refs #54

**Comment by Jolanrensen** [comment]
@asm0dey shall I add the other functions with backticks as well? It feels wrong to just have those two.

**Comment by asm0dey** [comment]
@Jolanrensen I think yes, @Meosit clearly stated that they think they may be useful, I think so too.

**Comment by Jolanrensen** [comment]
@asm0dey `==` calls `$eq$eq$eq`, so it should be `===` right? (it's called `equalTo()` in Java, different to `equals()` which uses 2 `=`s.

**Comment by asm0dey** [comment]
Yep, triple-eq definitely should be `===`

**Comment by Jolanrensen** [comment]
> Yep, triple-eq definitely should be `===`

@asm0dey Alright, I'll change that. Unfortunately `` `>` `` etc are not allowed since it's an illegal character :(. That can only be `gt`.

**Comment by asm0dey** [comment]
Can we use them without backticks, or `Column` already has `compareTo` method?

**Comment by Jolanrensen** [comment]
> Can we use them without backticks, or `Column` already has `compareTo` method?

@asm0dey Nope, because `compareTo` needs to return an `Int` and in the code `something < otherThing` will always return a `Boolean`. It cannot return a `Column` like in Scala.

**Comment by asm0dey** [comment]
Then we definitely have no choice which is good and bad at the same time :)

**Comment by Jolanrensen** [comment]
@asm0dey `` `||` `` is highlighted as "Name contains characters which can cause problems on Windows: |"... I'm not sure if this only becomes a problem when calling the function or just having it there.

**Comment by Jolanrensen** [comment]
@asm0dey alright, is there something I missed?

**Comment by asm0dey** [comment]
Thank you for your effort!

**Pull request merged**
