### PR TITLE
Spark 3.2

### PR DESCRIPTION
**Pull request by asm0dey**

### CODE REVIEW

**Comment by Jolanrensen** [comment]
Ah right! Let's see what qodana is complaining about

**Comment by asm0dey** [comment]
Also I can see that the buid fails. Will try to check tomorrow

**Comment by asm0dey** [comment]
OK, let the Qodana shut up

**Comment by Jolanrensen** [comment]
> OK, let the Qodana shut up

However the build of scala 12 still failed for some reason right?

**Comment by asm0dey** [comment]
Nop, it was qodana who failed the build and I just ignored it and submitted the issue to Qodana's issue tracker. Build goes fine and 1.0.3 should already be available in Central

**Pull request merged**
