### PR TITLE
Add Extensions for creating the Scala-Java-Wrapper

### PR DESCRIPTION
**Pull request by FelixEngl**
Hello Everyone,

it is just a simple Weapper for the JavaConversions Class.

It needs some unittests and a port to v3.0, i'll work on it around christmas. 

In the meantime i would be glad if you could give me some feedback what it needs and how you would test these conversions.

### CODE REVIEW

**Comment by asm0dey** [comment]
Shouldn't it be implemented inside `common` module?

**Comment by asm0dey** [comment]
Also, I don't really think functions should be inline.

**Comment by Jolanrensen** [comment]
I think this can be closed now, since the functionality is merged :)

**Comment by FelixEngl** [comment]
> I think this can be closed now, since the functionality is merged :)

Wonderful, sorry that i forgot to work on it. But at the moment i can't find the time for any "bigger" hobby programming project. ^^'

**Comment by asm0dey** [comment]
Thank y'all for your contributions!

**Pull request closed without merging**
